services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: caiobom/app-ordermanager:latest
    container_name: app_ordermanager
    environment:
      - AWS_SQS_QUEUE_URL=http://sqs.sa-east-1.localhost.localstack.cloud:4566/000000000000/order-queue
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=sa-east-1
      - AWS_DEFAULT_REGION=sa-east-1
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    networks:
      - app-network

networks:
  app-network:
    driver: bridge