services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=sa-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"